version: '3'
services:
  # redis:
  #   image: 'redis:latest'
  #   restart: always
  #   # container_name: test-redis
  #   networks:
  #     - test
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./external/redis:/data

  mongo:
    image: 'mongo:latest'
    restart: always
    # container_name: test-mongodb
    networks:
      - test
    ports:
      - 27017:27017
    volumes:
      - ./external/mongo:/data

  # rabbitmq:
  #   image: 'rabbitmq:latest'
  #   restart: always
  #   # container_name: test-rabbitmq
  #   networks:
  #     - test
  #   ports:
  #     - 5672:5672
  #   volumes:
  #     - ./external/rabbitmq:/data

  backend:
    container_name: test-mapmycustomers
    restart: always
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - JWT_SECRET=mysuperjwtsecret # JWT
      - APP_NAME="mapmycustomers_test" # For Bunyan
      - MONGO_LAB_DEV=mongodb://mongo/mapmycustomers_test
      - NODE_ENV=production
      - API_KEY='AIzaSyCQz-4BVOJd1kTCBkn7FDTy9hlxHzEkB2A'
      # - REDIS_URL=redis://redis
      # - AMQP_URL=amqp://rabbitmq
      - PORT=3000
    depends_on:
      - mongo
      # - redis
      # - rabbitmq
    networks:
      - test
    command: npm run dev
    ports:
      - 3000:3000

networks:
  test:
    driver: bridge
